version: '3'
services:
  webapp:
    build: .
    entrypoint: >
      bash -c " python3 /app/funcAPI/manage.py collectstatic --noi &&
                python3 /app/funcAPI/manage.py runserver 0:80"
    volumes:
      - .:/app
    ports:
      - "80:80"
    tty: true
